export const STORE_APPS = [
  {
    id: "calculator",
    name: "Calculator",
    category: "Utilities",
    desc: "Perform mathematical calculations.",
    rating: 4.5,
    icon: "calculator.png",
    native: true,
  },
  {
    id: "notes",
    name: "Notes",
    category: "Productivity",
    desc: "Capture thoughts, draw, and keep notes.",
    rating: 4.6,
    icon: "notes.png",
    native: true,
  },
  {
    id: "messages",
    name: "Messages",
    category: "Social",
    desc: "Connect with friends via iMessage.",
    rating: 4.4,
    icon: "message.png",
    native: true,
  },
  {
    id: "call",
    name: "FaceTime",
    category: "Social",
    desc: "Make audio and video calls.",
    rating: 4.7,
    icon: "call.png",
    native: true,
  },
  {
    id: "appletv",
    name: "Apple TV",
    category: "Entertainment",
    desc: "Watch Apple Originals and movies.",
    rating: 4.8,
    icon: "appletv.png",
    native: true,
  },
  {
    id: "safari",
    name: "Safari",
    category: "Utilities",
    desc: "Fast, secure, and private web browsing.",
    rating: 4.6,
    icon: "safari.png",
    native: true,
  },
  {
    id: "settings",
    name: "Settings",
    category: "Utilities",
    desc: "Customize system preferences.",
    rating: 4.3,
    icon: "settings.png",
    native: true,
  },
  {
    id: "calendar",
    name: "Calendar",
    category: "Productivity",
    desc: "Organize your schedule and tasks.",
    rating: 4.7,
    icon: "calendar.png",
    native: true,
  },
  {
    id: "resume",
    name: "Resume",
    category: "Productivity",
    desc: "View and download my professional resume.",
    rating: 4.9,
    icon: "pdf.png",
    native: true,
  },
  {
    id: "weather",
    name: "Weather",
    category: "Productivity",
    desc: "Real-time atmospheric forecasts and maps.",
    rating: 4.8,
    icon: "weather.png",
    native: true,
  },
  {
    id: "chrome",
    name: "Google Chrome",
    category: "Utilities",
    desc: "Fast, secure, and private web browsing.",
    rating: 4.8,
    icon: "chromee.png",
    native: true,
  },
  {
    id: "figma",
    name: "Figma",
    category: "Graphics & Design",
    desc: "Collaborative design & prototyping.",
    rating: 4.9,
    icon: "figma.png",
    native: false,
    url: "https://figma.com",
  },
  {
    id: "xcode",
    name: "Xcode",
    category: "Developer Tools",
    desc: "Integrated development for Apple platforms.",
    rating: 4.8,
    icon: "terminal.png",
    native: false,
  },
  {
    id: "vscode",
    name: "VS Code",
    category: "Developer Tools",
    desc: "Code editing. Redefined.",
    rating: 4.9,
    icon: "terminal.png",
    native: false,
  },
  {
    id: "notion",
    name: "Notion",
    category: "Productivity",
    desc: "Write, plan, and get organized.",
    rating: 4.7,
    icon: "plain.png",
    native: false,
  },
  {
    id: "slack",
    name: "Slack",
    category: "Business",
    desc: "Team communication and collaboration.",
    rating: 4.5,
    icon: "message.png",
    native: false,
  },
  {
    id: "asphalt",
    name: "Asphalt 9",
    category: "Games",
    desc: "Arcade racing game adventure.",
    rating: 4.7,
    icon: "photos.png",
    native: false,
    isGame: true,
  },
  {
    id: "tombraider",
    name: "Tomb Raider",
    category: "Games",
    desc: "Action adventure tomb exploration.",
    rating: 4.8,
    icon: "appletv.png",
    native: false,
    isGame: true,
  },
  {
    id: "minecraft",
    name: "Minecraft",
    category: "Games",
    desc: "Explore infinite worlds and build anything.",
    rating: 4.9,
    icon: "plain.png",
    native: false,
    isGame: true,
  },
  {
    id: "docker",
    name: "Docker Desktop",
    category: "Developer Tools",
    desc: "Build, run, and share containerized apps.",
    rating: 4.8,
    icon: "terminal.png",
    native: false,
  },
  {
    id: "postman",
    name: "Postman",
    category: "Developer Tools",
    desc: "API platform for building and using APIs.",
    rating: 4.7,
    icon: "postman.png",
    native: false,
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "Entertainment",
    desc: "Listen to millions of songs and podcasts.",
    rating: 4.7,
    icon: "music.png",
    native: false,
  },
  {
    id: "monumentvalley",
    name: "Monument Valley",
    category: "Games",
    desc: "Guide a silent princess through a beautiful world.",
    rating: 4.9,
    icon: "gal1.png",
    native: false,
    isGame: true,
  },
  {
    id: "subwaysurfers",
    name: "Subway Surfers",
    category: "Games",
    desc: "Dodge trains and dash as fast as you can.",
    rating: 4.6,
    icon: "gal2.png",
    native: false,
    isGame: true,
  },
];

export const FEATURED_APPS = [
  {
    id: "figma",
    title: "Collaborative Prototyping",
    subtitle: "Figma Design System",
    desc: "Design together in real time with high fidelity mockup tools.",
    bg: "from-purple-900/90 to-indigo-950/95",
    image: "appstore/figma_featured.png",
  },
  {
    id: "xcode",
    title: "IDE Redefined",
    subtitle: "Xcode 16 Developer Preview",
    desc: "Build applications with swift predictive compiler engines.",
    bg: "from-blue-950/90 to-slate-950/95",
    image: "wallpapers/wallpaper.png",
  },
];
